apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  labels:
    name: multicontainer
    environment: dev
    purpose: demo
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep",["1000"]]
