apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels: 
    name: roboshop
    tier: database
    environment: dev
spec:
- name: nginx
  image: nginx
  resources:
    requests:
      memory: "64mi"
      cpu: "100m"
    limits:
      memory: "128mi"
      cpu: "150m"
