apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels: 
    name: roboshop
    tier: database
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "150m"
